### ISSUE TITLE
Unresponsive background

### ISSUE THREAD

**Issue by fox3000foxy** [theupsilongirl/theupsilongirl.github.io#1]
![image](https://github.com/theupsilongirl/theupsilongirl.github.io/assets/40730498/dcd69e77-98b8-4559-bc59-03fa173015ca)
When i resized the window, i saw this.

The way you can fix it is to make you to the bottom of the picture and the background position from bottom right

**Comment by theupsilongirl** [comment]
Fixed in :
https://github.com/theupsilongirl/theupsilongirl.github.io/commit/6772012480ccf01a7d48b519dc2b529029b2696e
https://github.com/theupsilongirl/theupsilongirl.github.io/commit/1d7a82894ea61bde92cee05241c156e744a71499
https://github.com/theupsilongirl/theupsilongirl.github.io/commit/b0a1b0a4101e32f655444b7483b392c9bdcae1c4
https://github.com/theupsilongirl/theupsilongirl.github.io/commit/50c102896d6e9b9aab8b6989b9cadc89a6cf7bba
